defaultEntryPoints = ["http", "https"]

[entryPoints]
    [entryPoints.http]
      address = ":80"
      [entryPoints.http.redirect]
      entryPoint = "https"
    [entryPoints.https]
      address = ":443"
      [entryPoints.https.tls]

[acme]
[[acme.domains]]
  main = "myblogdomain.com"
  sans = ["monitor.myblogdomain.com", "api.myblogdomain.com", "www.myblogdomain.com"]
